version: 2.1

jobs:
  build-and-push:
    docker:
      # Any small Linux image is fine for issuing docker commands
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - checkout

      # Build Docker images inside a remote Docker engine
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      # Build all four images using your compose build file
      - run:
          name: Build images
          command: |
            docker compose -f docker-compose-build.yaml build --parallel

      # Tag images with both :latest and the commit SHA, then push
      - run:
          name: Tag and push images
          command: |
            SHA_TAG=${CIRCLE_SHA1:0:7}

            for IMAGE in udagram-api-user udagram-api-feed udagram-frontend reverseproxy; do
              docker tag kaminodev/$IMAGE:latest kaminodev/$IMAGE:$SHA_TAG
              docker push kaminodev/$IMAGE:latest
              docker push kaminodev/$IMAGE:$SHA_TAG
            done

workflows:
  version: 2
  build_on_main:
    jobs:
      - build-and-push:
          filters:
            branches:
              only: main
