apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: udagram
spec:
  replicas: 2
  selector: { matchLabels: { app: frontend } }
  template:
    metadata: { labels: { app: frontend } }
    spec:
      containers:
        - name: frontend
          image: kaminodev/udagram-frontend:latest
          ports: [{ containerPort: 80 }]
          readinessProbe: { httpGet: { path: "/", port: 80 }, initialDelaySeconds: 5, periodSeconds: 10 }
          livenessProbe:  { httpGet: { path: "/", port: 80 }, initialDelaySeconds: 15, periodSeconds: 20 }
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: udagram
spec:
  type: ClusterIP
  selector: { app: frontend }
  ports: [{ name: http, port: 80, targetPort: 80 }]
