apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: udagram-eks
  region: us-east-1
  version: "1.29"

iam:
  withOIDC: true

vpc:
  nat:
    gateway: Single

managedNodeGroups:
  - name: ng-general
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 3
    maxSize: 6
    volumeSize: 30
    privateNetworking: true
    labels:
      role: general
